#!/bin/sh
echo "-------------- RME Building Process --------------"
echo ""
echo "----------- Begin RME Compiling Process ----------"
echo ""
ant -buildfile java/upmt/peerBuild.xml
#javac java/upmt/src/upmt/peer/RMEPeer.java -classpath /home/upmt/upmt-devel/java/upmt/bin:/home/upmt/upmt-devel/java/upmt/lib/junit.jar:/home/upmt/upmt-devel/java/upmt/lib/matthew.jar:/home/upmt/upmt-devel/java/upmt/lib/slf4j-api-1.5.6.jar:/home/upmt/upmt-devel/java/upmt/lib/slf4j-jdk14-1.5.6.jar:/home/upmt/upmt-devel/java/upmt/lib/jchart2d-3.2.0.jar:/home/upmt/upmt-devel/java/upmt/lib/android.jar:/home/upmt/upmt-devel/java/upmt/lib/jcommon-1.0.17.jar:/home/upmt/upmt-devel/java/upmt/lib/jfreechart-1.0.14.jar:/home/upmt/upmt-devel/java/upmt/lib/dbus-2.8.jar:/home/upmt/upmt-devel/java/upmt/lib/jmf.jar
echo ""
echo "------------ END RME Compiling Process -----------"
echo ""
echo "-------------- Creating RMEPeer.jar --------------"
echo ""
ant -buildfile java/upmt/build.xml
echo ""
echo "-------------- RMEPeer.jar Created--------------"

